//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.OrderDelivery = new HashSet<OrderDelivery>();
        }
    
        public int id { get; set; }
        public string region { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
    
        public virtual ICollection<OrderDelivery> OrderDelivery { get; set; }
    }
}
