//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeType
    {
        public ChangeType()
        {
            this.StoreGoods = new HashSet<StoreGoods>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<StoreGoods> StoreGoods { get; set; }
    }
}
