//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.StoreGoods = new HashSet<StoreGoods>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public string date { get; set; }
        public int DocumentType_id { get; set; }
        public int Store_name { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<StoreGoods> StoreGoods { get; set; }
    }
}
