//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        public Duty()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int EmployeePost_idPost { get; set; }
        public int EmployeePerson_idPerson { get; set; }
        public string idDuty { get; set; }
        public string hours { get; set; }
        public string deduction { get; set; }
        public string promotion { get; set; }
        public string note { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
