//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomenclature
    {
        public Nomenclature()
        {
            this.ProductCompose = new HashSet<ProductCompose>();
            this.ProductCompose1 = new HashSet<ProductCompose>();
            this.StoreGoods = new HashSet<StoreGoods>();
        }
    
        public int idNom { get; set; }
        public string priceIn { get; set; }
        public string priceOut { get; set; }
        public string menuPresence { get; set; }
        public string description { get; set; }
        public int UnitDimention_name { get; set; }
        public int CategoryIdCategory { get; set; }
    
        public virtual UnitDimention UnitDimention { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductCompose> ProductCompose { get; set; }
        public virtual ICollection<ProductCompose> ProductCompose1 { get; set; }
        public virtual ICollection<StoreGoods> StoreGoods { get; set; }
    }
}
