//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int OrderStatus_idState { get; set; }
        public int Person_idPerson { get; set; }
        public string DateTime { get; set; }
        public int DeliveryType_idType { get; set; }
        public int OrderDelivery_id { get; set; }
        public int Place_id { get; set; }
        public string sale { get; set; }
        public string Duty_idDuty { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Person Person { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual OrderDelivery OrderDelivery { get; set; }
        public virtual Place Place { get; set; }
        public virtual Duty Duty { get; set; }
    }
}
