//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasport
    {
        public int number { get; set; }
        public string getDate { get; set; }
        public string giver { get; set; }
        public int PersonIdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
