//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.User = new HashSet<User>();
            this.Pasport = new HashSet<Pasport>();
            this.Employee = new HashSet<Employee>();
            this.Order = new HashSet<Order>();
        }
    
        public int idPerson { get; set; }
        public string name { get; set; }
        public string telNum { get; set; }
        public string birthDate { get; set; }
        public string snils { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Pasport> Pasport { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
