//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreGoods
    {
        public string dateTime { get; set; }
        public string quantity { get; set; }
        public int ChangeType_id { get; set; }
        public int Document_id { get; set; }
        public int Store_name { get; set; }
        public int Nomenclature_idNom { get; set; }
    
        public virtual ChangeType ChangeType { get; set; }
        public virtual Document Document { get; set; }
        public virtual Store Store { get; set; }
        public virtual Nomenclature Nomenclature { get; set; }
    }
}
