//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Store2 = new HashSet<Store>();
            this.Document = new HashSet<Document>();
            this.StoreGoods = new HashSet<StoreGoods>();
        }
    
        public int name { get; set; }
        public string description { get; set; }
        public int Store_name { get; set; }
    
        public virtual Store Store1 { get; set; }
        public virtual ICollection<Store> Store2 { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<StoreGoods> StoreGoods { get; set; }
    }
}
