//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitDimention
    {
        public UnitDimention()
        {
            this.Nomenclature = new HashSet<Nomenclature>();
            this.ProductCompose = new HashSet<ProductCompose>();
        }
    
        public int name { get; set; }
    
        public virtual ICollection<Nomenclature> Nomenclature { get; set; }
        public virtual ICollection<ProductCompose> ProductCompose { get; set; }
    }
}
